name: "size"
on:
  pull_request:
    branches: [ master ]

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Using Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: npm ci
    - uses: andresz1/size-limit-action@v1.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_step: install